### ISSUE TITLE
保存文章时分类错误

### ISSUE THREAD

**Issue by Hellobaka** [Hellobaka/HexoArticleEditor#1]
保存后正常分类变得错误

**Comment by Hellobaka** [comment]
由于原始文件的目录为双层导致
```yaml
title: Chrome Cookie解密
tags: []
id: '292'
categories:
  - - C#
  - - 前端杂项
date: 2023-07-16 16:29:50
cover: images/post/2023/07/101021338_p0.jpg
```
